# archived @Jan 31, 2021 at 7:54 pm
# borrowed from https://raw.githubusercontent.com/bitnami/bitnami-docker-laravel/master/docker-compose.yml
version: '2'

services:
  mariadb:
    image: bitnami/mariadb:10.2-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
  challenge:
    tty: true
    image: bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
    - "./EncryptCookies.php:/tmp/app/app/Http/Middleware/EncryptCookies.php"
    - "./flag:/flag"
